/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-06 at 20:41:18 UTC 
 * Modify at your own risk.
 */

package org.mivotocuenta.server.ws.wsgestionusuario.model;

/**
 * Model definition for Usuario.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the wsgestionusuario. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Usuario extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String apellidos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String correo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idUsuario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombres;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long version;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getApellidos() {
    return apellidos;
  }

  /**
   * @param apellidos apellidos or {@code null} for none
   */
  public Usuario setApellidos(java.lang.String apellidos) {
    this.apellidos = apellidos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCorreo() {
    return correo;
  }

  /**
   * @param correo correo or {@code null} for none
   */
  public Usuario setCorreo(java.lang.String correo) {
    this.correo = correo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdUsuario() {
    return idUsuario;
  }

  /**
   * @param idUsuario idUsuario or {@code null} for none
   */
  public Usuario setIdUsuario(java.lang.Long idUsuario) {
    this.idUsuario = idUsuario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombres() {
    return nombres;
  }

  /**
   * @param nombres nombres or {@code null} for none
   */
  public Usuario setNombres(java.lang.String nombres) {
    this.nombres = nombres;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOperacion() {
    return operacion;
  }

  /**
   * @param operacion operacion or {@code null} for none
   */
  public Usuario setOperacion(java.lang.String operacion) {
    this.operacion = operacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVersion() {
    return version;
  }

  /**
   * @param version version or {@code null} for none
   */
  public Usuario setVersion(java.lang.Long version) {
    this.version = version;
    return this;
  }

  @Override
  public Usuario set(String fieldName, Object value) {
    return (Usuario) super.set(fieldName, value);
  }

  @Override
  public Usuario clone() {
    return (Usuario) super.clone();
  }

}
