/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-06 at 20:41:07 UTC 
 * Modify at your own risk.
 */

package org.mivotocuenta.server.ws.wsgestionconteo;

/**
 * Service definition for Wsgestionconteo (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link WsgestionconteoRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Wsgestionconteo extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the wsgestionconteo library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://webmivotocuenta.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "wsgestionconteo/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Wsgestionconteo(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Wsgestionconteo(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getConteo".
   *
   * This request holds the parameters needed by the wsgestionconteo server.  After setting any
   * optional parameters, call the {@link GetConteo#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetConteo getConteo(java.lang.Long id) throws java.io.IOException {
    GetConteo result = new GetConteo(id);
    initialize(result);
    return result;
  }

  public class GetConteo extends WsgestionconteoRequest<org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo> {

    private static final String REST_PATH = "conteo/{id}";

    /**
     * Create a request for the method "getConteo".
     *
     * This request holds the parameters needed by the the wsgestionconteo server.  After setting any
     * optional parameters, call the {@link GetConteo#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetConteo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetConteo(java.lang.Long id) {
      super(Wsgestionconteo.this, "GET", REST_PATH, null, org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetConteo setAlt(java.lang.String alt) {
      return (GetConteo) super.setAlt(alt);
    }

    @Override
    public GetConteo setFields(java.lang.String fields) {
      return (GetConteo) super.setFields(fields);
    }

    @Override
    public GetConteo setKey(java.lang.String key) {
      return (GetConteo) super.setKey(key);
    }

    @Override
    public GetConteo setOauthToken(java.lang.String oauthToken) {
      return (GetConteo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetConteo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetConteo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetConteo setQuotaUser(java.lang.String quotaUser) {
      return (GetConteo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetConteo setUserIp(java.lang.String userIp) {
      return (GetConteo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetConteo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetConteo set(String parameterName, Object value) {
      return (GetConteo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertConteo".
   *
   * This request holds the parameters needed by the wsgestionconteo server.  After setting any
   * optional parameters, call the {@link InsertConteo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo}
   * @return the request
   */
  public InsertConteo insertConteo(org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo content) throws java.io.IOException {
    InsertConteo result = new InsertConteo(content);
    initialize(result);
    return result;
  }

  public class InsertConteo extends WsgestionconteoRequest<org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo> {

    private static final String REST_PATH = "conteo";

    /**
     * Create a request for the method "insertConteo".
     *
     * This request holds the parameters needed by the the wsgestionconteo server.  After setting any
     * optional parameters, call the {@link InsertConteo#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertConteo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo}
     * @since 1.13
     */
    protected InsertConteo(org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo content) {
      super(Wsgestionconteo.this, "POST", REST_PATH, content, org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo.class);
    }

    @Override
    public InsertConteo setAlt(java.lang.String alt) {
      return (InsertConteo) super.setAlt(alt);
    }

    @Override
    public InsertConteo setFields(java.lang.String fields) {
      return (InsertConteo) super.setFields(fields);
    }

    @Override
    public InsertConteo setKey(java.lang.String key) {
      return (InsertConteo) super.setKey(key);
    }

    @Override
    public InsertConteo setOauthToken(java.lang.String oauthToken) {
      return (InsertConteo) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertConteo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertConteo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertConteo setQuotaUser(java.lang.String quotaUser) {
      return (InsertConteo) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertConteo setUserIp(java.lang.String userIp) {
      return (InsertConteo) super.setUserIp(userIp);
    }

    @Override
    public InsertConteo set(String parameterName, Object value) {
      return (InsertConteo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listConteo".
   *
   * This request holds the parameters needed by the wsgestionconteo server.  After setting any
   * optional parameters, call the {@link ListConteo#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListConteo listConteo() throws java.io.IOException {
    ListConteo result = new ListConteo();
    initialize(result);
    return result;
  }

  public class ListConteo extends WsgestionconteoRequest<org.mivotocuenta.server.ws.wsgestionconteo.model.CollectionResponseConteo> {

    private static final String REST_PATH = "conteo";

    /**
     * Create a request for the method "listConteo".
     *
     * This request holds the parameters needed by the the wsgestionconteo server.  After setting any
     * optional parameters, call the {@link ListConteo#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListConteo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListConteo() {
      super(Wsgestionconteo.this, "GET", REST_PATH, null, org.mivotocuenta.server.ws.wsgestionconteo.model.CollectionResponseConteo.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListConteo setAlt(java.lang.String alt) {
      return (ListConteo) super.setAlt(alt);
    }

    @Override
    public ListConteo setFields(java.lang.String fields) {
      return (ListConteo) super.setFields(fields);
    }

    @Override
    public ListConteo setKey(java.lang.String key) {
      return (ListConteo) super.setKey(key);
    }

    @Override
    public ListConteo setOauthToken(java.lang.String oauthToken) {
      return (ListConteo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListConteo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListConteo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListConteo setQuotaUser(java.lang.String quotaUser) {
      return (ListConteo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListConteo setUserIp(java.lang.String userIp) {
      return (ListConteo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListConteo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListConteo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListConteo set(String parameterName, Object value) {
      return (ListConteo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeConteo".
   *
   * This request holds the parameters needed by the wsgestionconteo server.  After setting any
   * optional parameters, call the {@link RemoveConteo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveConteo removeConteo(java.lang.Long id) throws java.io.IOException {
    RemoveConteo result = new RemoveConteo(id);
    initialize(result);
    return result;
  }

  public class RemoveConteo extends WsgestionconteoRequest<Void> {

    private static final String REST_PATH = "conteo/{id}";

    /**
     * Create a request for the method "removeConteo".
     *
     * This request holds the parameters needed by the the wsgestionconteo server.  After setting any
     * optional parameters, call the {@link RemoveConteo#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveConteo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveConteo(java.lang.Long id) {
      super(Wsgestionconteo.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveConteo setAlt(java.lang.String alt) {
      return (RemoveConteo) super.setAlt(alt);
    }

    @Override
    public RemoveConteo setFields(java.lang.String fields) {
      return (RemoveConteo) super.setFields(fields);
    }

    @Override
    public RemoveConteo setKey(java.lang.String key) {
      return (RemoveConteo) super.setKey(key);
    }

    @Override
    public RemoveConteo setOauthToken(java.lang.String oauthToken) {
      return (RemoveConteo) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveConteo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveConteo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveConteo setQuotaUser(java.lang.String quotaUser) {
      return (RemoveConteo) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveConteo setUserIp(java.lang.String userIp) {
      return (RemoveConteo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveConteo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveConteo set(String parameterName, Object value) {
      return (RemoveConteo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateConteo".
   *
   * This request holds the parameters needed by the wsgestionconteo server.  After setting any
   * optional parameters, call the {@link UpdateConteo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo}
   * @return the request
   */
  public UpdateConteo updateConteo(org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo content) throws java.io.IOException {
    UpdateConteo result = new UpdateConteo(content);
    initialize(result);
    return result;
  }

  public class UpdateConteo extends WsgestionconteoRequest<org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo> {

    private static final String REST_PATH = "conteo";

    /**
     * Create a request for the method "updateConteo".
     *
     * This request holds the parameters needed by the the wsgestionconteo server.  After setting any
     * optional parameters, call the {@link UpdateConteo#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateConteo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo}
     * @since 1.13
     */
    protected UpdateConteo(org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo content) {
      super(Wsgestionconteo.this, "PUT", REST_PATH, content, org.mivotocuenta.server.ws.wsgestionconteo.model.Conteo.class);
    }

    @Override
    public UpdateConteo setAlt(java.lang.String alt) {
      return (UpdateConteo) super.setAlt(alt);
    }

    @Override
    public UpdateConteo setFields(java.lang.String fields) {
      return (UpdateConteo) super.setFields(fields);
    }

    @Override
    public UpdateConteo setKey(java.lang.String key) {
      return (UpdateConteo) super.setKey(key);
    }

    @Override
    public UpdateConteo setOauthToken(java.lang.String oauthToken) {
      return (UpdateConteo) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateConteo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateConteo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateConteo setQuotaUser(java.lang.String quotaUser) {
      return (UpdateConteo) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateConteo setUserIp(java.lang.String userIp) {
      return (UpdateConteo) super.setUserIp(userIp);
    }

    @Override
    public UpdateConteo set(String parameterName, Object value) {
      return (UpdateConteo) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Wsgestionconteo}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Wsgestionconteo}. */
    @Override
    public Wsgestionconteo build() {
      return new Wsgestionconteo(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link WsgestionconteoRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setWsgestionconteoRequestInitializer(
        WsgestionconteoRequestInitializer wsgestionconteoRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(wsgestionconteoRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
