/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-06 at 20:41:13 UTC 
 * Modify at your own risk.
 */

package org.mivotocuenta.server.ws.wsgestioncandidato.model;

/**
 * Model definition for Candidato.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the wsgestioncandidato. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Candidato extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String candidato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idCandidato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String linkFotoCandidato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String linkFotoPartido;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String linkPlanGobierno;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombrePartido;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long version;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCandidato() {
    return candidato;
  }

  /**
   * @param candidato candidato or {@code null} for none
   */
  public Candidato setCandidato(java.lang.String candidato) {
    this.candidato = candidato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdCandidato() {
    return idCandidato;
  }

  /**
   * @param idCandidato idCandidato or {@code null} for none
   */
  public Candidato setIdCandidato(java.lang.Long idCandidato) {
    this.idCandidato = idCandidato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLinkFotoCandidato() {
    return linkFotoCandidato;
  }

  /**
   * @param linkFotoCandidato linkFotoCandidato or {@code null} for none
   */
  public Candidato setLinkFotoCandidato(java.lang.String linkFotoCandidato) {
    this.linkFotoCandidato = linkFotoCandidato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLinkFotoPartido() {
    return linkFotoPartido;
  }

  /**
   * @param linkFotoPartido linkFotoPartido or {@code null} for none
   */
  public Candidato setLinkFotoPartido(java.lang.String linkFotoPartido) {
    this.linkFotoPartido = linkFotoPartido;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLinkPlanGobierno() {
    return linkPlanGobierno;
  }

  /**
   * @param linkPlanGobierno linkPlanGobierno or {@code null} for none
   */
  public Candidato setLinkPlanGobierno(java.lang.String linkPlanGobierno) {
    this.linkPlanGobierno = linkPlanGobierno;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombrePartido() {
    return nombrePartido;
  }

  /**
   * @param nombrePartido nombrePartido or {@code null} for none
   */
  public Candidato setNombrePartido(java.lang.String nombrePartido) {
    this.nombrePartido = nombrePartido;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOperacion() {
    return operacion;
  }

  /**
   * @param operacion operacion or {@code null} for none
   */
  public Candidato setOperacion(java.lang.String operacion) {
    this.operacion = operacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVersion() {
    return version;
  }

  /**
   * @param version version or {@code null} for none
   */
  public Candidato setVersion(java.lang.Long version) {
    this.version = version;
    return this;
  }

  @Override
  public Candidato set(String fieldName, Object value) {
    return (Candidato) super.set(fieldName, value);
  }

  @Override
  public Candidato clone() {
    return (Candidato) super.clone();
  }

}
