/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-06 at 20:41:13 UTC 
 * Modify at your own risk.
 */

package org.mivotocuenta.server.ws.wsgestioncandidato;

/**
 * Service definition for Wsgestioncandidato (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link WsgestioncandidatoRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Wsgestioncandidato extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the wsgestioncandidato library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://webmivotocuenta.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "wsgestioncandidato/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Wsgestioncandidato(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Wsgestioncandidato(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCandidato".
   *
   * This request holds the parameters needed by the wsgestioncandidato server.  After setting any
   * optional parameters, call the {@link GetCandidato#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetCandidato getCandidato(java.lang.Long id) throws java.io.IOException {
    GetCandidato result = new GetCandidato(id);
    initialize(result);
    return result;
  }

  public class GetCandidato extends WsgestioncandidatoRequest<org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato> {

    private static final String REST_PATH = "candidato/{id}";

    /**
     * Create a request for the method "getCandidato".
     *
     * This request holds the parameters needed by the the wsgestioncandidato server.  After setting
     * any optional parameters, call the {@link GetCandidato#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetCandidato#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCandidato(java.lang.Long id) {
      super(Wsgestioncandidato.this, "GET", REST_PATH, null, org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCandidato setAlt(java.lang.String alt) {
      return (GetCandidato) super.setAlt(alt);
    }

    @Override
    public GetCandidato setFields(java.lang.String fields) {
      return (GetCandidato) super.setFields(fields);
    }

    @Override
    public GetCandidato setKey(java.lang.String key) {
      return (GetCandidato) super.setKey(key);
    }

    @Override
    public GetCandidato setOauthToken(java.lang.String oauthToken) {
      return (GetCandidato) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCandidato setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCandidato) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCandidato setQuotaUser(java.lang.String quotaUser) {
      return (GetCandidato) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCandidato setUserIp(java.lang.String userIp) {
      return (GetCandidato) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCandidato setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCandidato set(String parameterName, Object value) {
      return (GetCandidato) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCandidato".
   *
   * This request holds the parameters needed by the wsgestioncandidato server.  After setting any
   * optional parameters, call the {@link InsertCandidato#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato}
   * @return the request
   */
  public InsertCandidato insertCandidato(org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato content) throws java.io.IOException {
    InsertCandidato result = new InsertCandidato(content);
    initialize(result);
    return result;
  }

  public class InsertCandidato extends WsgestioncandidatoRequest<org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato> {

    private static final String REST_PATH = "candidato";

    /**
     * Create a request for the method "insertCandidato".
     *
     * This request holds the parameters needed by the the wsgestioncandidato server.  After setting
     * any optional parameters, call the {@link InsertCandidato#execute()} method to invoke the remote
     * operation. <p> {@link InsertCandidato#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato}
     * @since 1.13
     */
    protected InsertCandidato(org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato content) {
      super(Wsgestioncandidato.this, "POST", REST_PATH, content, org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato.class);
    }

    @Override
    public InsertCandidato setAlt(java.lang.String alt) {
      return (InsertCandidato) super.setAlt(alt);
    }

    @Override
    public InsertCandidato setFields(java.lang.String fields) {
      return (InsertCandidato) super.setFields(fields);
    }

    @Override
    public InsertCandidato setKey(java.lang.String key) {
      return (InsertCandidato) super.setKey(key);
    }

    @Override
    public InsertCandidato setOauthToken(java.lang.String oauthToken) {
      return (InsertCandidato) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCandidato setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCandidato) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCandidato setQuotaUser(java.lang.String quotaUser) {
      return (InsertCandidato) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCandidato setUserIp(java.lang.String userIp) {
      return (InsertCandidato) super.setUserIp(userIp);
    }

    @Override
    public InsertCandidato set(String parameterName, Object value) {
      return (InsertCandidato) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCandidato".
   *
   * This request holds the parameters needed by the wsgestioncandidato server.  After setting any
   * optional parameters, call the {@link ListCandidato#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListCandidato listCandidato() throws java.io.IOException {
    ListCandidato result = new ListCandidato();
    initialize(result);
    return result;
  }

  public class ListCandidato extends WsgestioncandidatoRequest<org.mivotocuenta.server.ws.wsgestioncandidato.model.CollectionResponseCandidato> {

    private static final String REST_PATH = "candidato";

    /**
     * Create a request for the method "listCandidato".
     *
     * This request holds the parameters needed by the the wsgestioncandidato server.  After setting
     * any optional parameters, call the {@link ListCandidato#execute()} method to invoke the remote
     * operation. <p> {@link ListCandidato#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCandidato() {
      super(Wsgestioncandidato.this, "GET", REST_PATH, null, org.mivotocuenta.server.ws.wsgestioncandidato.model.CollectionResponseCandidato.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCandidato setAlt(java.lang.String alt) {
      return (ListCandidato) super.setAlt(alt);
    }

    @Override
    public ListCandidato setFields(java.lang.String fields) {
      return (ListCandidato) super.setFields(fields);
    }

    @Override
    public ListCandidato setKey(java.lang.String key) {
      return (ListCandidato) super.setKey(key);
    }

    @Override
    public ListCandidato setOauthToken(java.lang.String oauthToken) {
      return (ListCandidato) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCandidato setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCandidato) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCandidato setQuotaUser(java.lang.String quotaUser) {
      return (ListCandidato) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCandidato setUserIp(java.lang.String userIp) {
      return (ListCandidato) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCandidato setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListCandidato setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListCandidato set(String parameterName, Object value) {
      return (ListCandidato) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeCandidato".
   *
   * This request holds the parameters needed by the wsgestioncandidato server.  After setting any
   * optional parameters, call the {@link RemoveCandidato#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveCandidato removeCandidato(java.lang.Long id) throws java.io.IOException {
    RemoveCandidato result = new RemoveCandidato(id);
    initialize(result);
    return result;
  }

  public class RemoveCandidato extends WsgestioncandidatoRequest<Void> {

    private static final String REST_PATH = "candidato/{id}";

    /**
     * Create a request for the method "removeCandidato".
     *
     * This request holds the parameters needed by the the wsgestioncandidato server.  After setting
     * any optional parameters, call the {@link RemoveCandidato#execute()} method to invoke the remote
     * operation. <p> {@link RemoveCandidato#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveCandidato(java.lang.Long id) {
      super(Wsgestioncandidato.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveCandidato setAlt(java.lang.String alt) {
      return (RemoveCandidato) super.setAlt(alt);
    }

    @Override
    public RemoveCandidato setFields(java.lang.String fields) {
      return (RemoveCandidato) super.setFields(fields);
    }

    @Override
    public RemoveCandidato setKey(java.lang.String key) {
      return (RemoveCandidato) super.setKey(key);
    }

    @Override
    public RemoveCandidato setOauthToken(java.lang.String oauthToken) {
      return (RemoveCandidato) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveCandidato setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveCandidato) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveCandidato setQuotaUser(java.lang.String quotaUser) {
      return (RemoveCandidato) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveCandidato setUserIp(java.lang.String userIp) {
      return (RemoveCandidato) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveCandidato setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveCandidato set(String parameterName, Object value) {
      return (RemoveCandidato) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCandidato".
   *
   * This request holds the parameters needed by the wsgestioncandidato server.  After setting any
   * optional parameters, call the {@link UpdateCandidato#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato}
   * @return the request
   */
  public UpdateCandidato updateCandidato(org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato content) throws java.io.IOException {
    UpdateCandidato result = new UpdateCandidato(content);
    initialize(result);
    return result;
  }

  public class UpdateCandidato extends WsgestioncandidatoRequest<org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato> {

    private static final String REST_PATH = "candidato";

    /**
     * Create a request for the method "updateCandidato".
     *
     * This request holds the parameters needed by the the wsgestioncandidato server.  After setting
     * any optional parameters, call the {@link UpdateCandidato#execute()} method to invoke the remote
     * operation. <p> {@link UpdateCandidato#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato}
     * @since 1.13
     */
    protected UpdateCandidato(org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato content) {
      super(Wsgestioncandidato.this, "PUT", REST_PATH, content, org.mivotocuenta.server.ws.wsgestioncandidato.model.Candidato.class);
    }

    @Override
    public UpdateCandidato setAlt(java.lang.String alt) {
      return (UpdateCandidato) super.setAlt(alt);
    }

    @Override
    public UpdateCandidato setFields(java.lang.String fields) {
      return (UpdateCandidato) super.setFields(fields);
    }

    @Override
    public UpdateCandidato setKey(java.lang.String key) {
      return (UpdateCandidato) super.setKey(key);
    }

    @Override
    public UpdateCandidato setOauthToken(java.lang.String oauthToken) {
      return (UpdateCandidato) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCandidato setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCandidato) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCandidato setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCandidato) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCandidato setUserIp(java.lang.String userIp) {
      return (UpdateCandidato) super.setUserIp(userIp);
    }

    @Override
    public UpdateCandidato set(String parameterName, Object value) {
      return (UpdateCandidato) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Wsgestioncandidato}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Wsgestioncandidato}. */
    @Override
    public Wsgestioncandidato build() {
      return new Wsgestioncandidato(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link WsgestioncandidatoRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setWsgestioncandidatoRequestInitializer(
        WsgestioncandidatoRequestInitializer wsgestioncandidatoRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(wsgestioncandidatoRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
